export const ADD_TASK = 'ADD_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const EDIT_TASK = 'EDIT_TASK'

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const EDIT_USER = 'EDIT_USER'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const EDIT_POST = 'EDIT_POST'
export const DELETE_POST = 'DELETE_POST'


export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'
export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'